
export enum SeSubmissionStatus{
  EXECUTION = 3,
  EXECUTING_JUDGE = 5,
  COMPILATION_ERROR = 11,
  RUNTIME_ERROR = 12,
  TIME_LIMIT_EXCEEDED = 13,
  WRONG_ANSWER = 14,
  ACCEPTED = 15,
  MEMORY_LIMIT_EXCEEDED = 17,
  ILLEGAL_SYSTEM_CALL = 19,
  INTERNAL_ERROR = 20
}
